### PR TITLE
fixed redirected for media and static files if external https reverse proxy is used

### PR DESCRIPTION
**Pull request by anddann**
Hi, 
I use the following setup for running taiga:
- Nginx with Let's Encrypt
- Taiga runs inside a docker container with `TAIGA_SSL_BY_REVERSE_PROXY` set to `True`
For the given setup I've encountered the problems, that
- the admin interface under `your.domain.com/admin` does not work because it tries to locate files using http and then fails
- the media and static files are still delivered over http, which causes firefox and chrome to raise the alarm mixed content

This pull request, fixes the issue by setting the media and static urls to https, too.

PS: Thank you @ajira86 for actively working on this useful docker container!

### CODE REVIEW

**Comment by ajira86** [comment]
Sorry for the delay but I never used this Taiga container in SSL mode. So I'm trying to setup it from two weeks with docker-compose and a self-signed certificate but even if system is working without SSL when I switch to SSL nginx stops to answer to my query (nothing in access nor error logs).

**Comment by anddann** [comment]
actually, I've never used to SSL switch but only used the SSL_Reverse_PROXY switch for a lecture, where 160 students use taiga.

**Comment by ajira86** [comment]
I found an error in Nginx configuration if you run SSL without taiga events. Are you using taiga-events by default ?

**Comment by anddann** [comment]
Nope, I don't use taiga event.

**Comment by ajira86** [comment]
Thanks for your PR, I merged it with image in version 3.3.13.
Because I don't especially use a proxy with Nginx feel free to confirm if all is ok from your side.
Note: I didn't found a way to access to django admin area, is there a specifiy way to access/enable it ?

**Comment by anddann** [comment]
for accessing the admin interface try `mydomain.com/admin/` note the slash at the end

**Pull request merged**
